type: php
docroot: .Build
additional_hostnames:
  - 12.typo3-styleguide
  - 13.typo3-styleguide
hooks:
   post-start:
    - exec: mkdir -p /var/www/html/.Build/ && cp /var/www/html/.ddev/.setup/templates/* /var/www/html/.Build/
